config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :transactions
  resources :credits
  namespace :admin do
    resources :users
    resources :announcements
    resources :notifications
    resources :services
    root to: 'users#index'
  end

  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)
    @transaction.user = current_user
    if @transaction.save
      redirect_to @transaction, notice: 'Transaction was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:user_id, :description, :type, :price_cents)
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.haml
= simple_form_for(transaction) do |form|
  = form.input :description
  = form.input :type, as: :string
  = form.input :price_cents
  .form-group
    - if transaction.persisted?
      .float-right
        = link_to 'Destroy', transaction, method: :delete, class: "text-danger", data: { confirm: 'Are you sure?' }
    = form.submit class: 'btn btn-primary'
    - if transaction.persisted?
      = link_to "Cancel", transaction, class: "btn btn-link"
    - else
      = link_to "Cancel", transactions_path, class: "btn btn-link"

app/views/transactions/edit.html.haml
%h1 Edit Transaction
= render 'form', transaction: @transaction

app/views/transactions/index.html.haml
.row
  .col-sm-6
    %h1 Transactions
  .col-sm-6.text-right
    = link_to new_transaction_path, class: 'btn btn-primary' do
      Add New Transaction
.table-responsive
  %table.table.table-striped.table-bordered.table-hover
    %thead
      %tr
        %th User
        %th Description
        %th Type
        %th Price cents
        %th
    %tbody
      - @transactions.each do |transaction|
        = content_tag :tr, id: dom_id(transaction), class: dom_class(transaction) do
          %td= transaction.user.name
          %td= transaction.description
          %td= transaction.type
          %td= transaction.price_cents
          %td= link_to 'Show', transaction

app/views/transactions/new.html.haml
= render 'form', transaction: @transaction

app/views/transactions/show.html.haml
.page-header
  = link_to transactions_path, class: 'btn btn-default' do
    %span.glyphicon.glyphicon-list-alt
    All Transactions
  = link_to edit_transaction_path(@transaction), class: 'btn btn-primary' do
    %span.glyphicon.glyphicon-pencil
    Edit
  %h1 Show transaction
%dl.dl-horizontal
  %dt User:
  %dd= @transaction.user
  %dt Description:
  %dd= @transaction.description
  %dt Type:
  %dd= @transaction.type
  %dt Price cents:
  %dd= @transaction.price_cents